In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [2]:
carros = pd.read_csv("base_de_dados_carro.csv")

In [3]:
carros.drop(columns="torque", inplace=True)

In [4]:
#renomeando cada coluna para ptbr
colunas_traduzidas = {
    "name": "nome",
    "year": "ano",
    "selling_price": "preco_venda",
    "km_driven": "km_rodados",
    "fuel": "combustivel",
    "seller_type": "tipo_vendedor",
    "transmission": "transmissao",
    "owner": "proprietario",
    "mileage": "consumo",
    "engine": "motor",
    "max_power": "potencia_maxima",
    "seats": "assentos"
}
carros = carros.rename(columns=colunas_traduzidas)
carros.head(5)

nome   ano  preco_venda  km_rodados combustivel  \
0        Maruti Swift Dzire VDI  2014       450000      145500      Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014       370000      120000      Diesel   
2      Honda City 2017-2020 EXi  2006       158000      140000      Petrol   
3     Hyundai i20 Sportz Diesel  2010       225000      127000      Diesel   
4        Maruti Swift VXI BSIII  2007       130000      120000      Petrol   

  tipo_vendedor transmissao  proprietario     consumo    motor  \
0    Individual      Manual   First Owner   23.4 kmpl  1248 CC   
1    Individual      Manual  Second Owner  21.14 kmpl  1498 CC   
2    Individual      Manual   Third Owner   17.7 kmpl  1497 CC   
3    Individual      Manual   First Owner   23.0 kmpl  1396 CC   
4    Individual      Manual   First Owner   16.1 kmpl  1298 CC   

  potencia_maxima  assentos  
0          74 bhp       5.0  
1      103.52 bhp       5.0  
2          78 bhp       5.0  
3          90 bhp       5.0  
4        88.2 bhp       5.0

In [5]:
#pré processamento

In [6]:
#Retirando Nulos
carros.dropna(inplace= True)

In [7]:
#Retirando Duplicadas
carros.drop_duplicates (inplace=True)

In [8]:
#Pegando o nome da marca de cada carro
def pegar_marca_do_carro(nome_do_carro):
    nome_do_carro = nome_do_carro.split(' ')[0] 
    return nome_do_carro.strip(' ')

In [9]:
#Pegando o nome da marca de cada carro
def limpar_dado(dado):
    dado = dado.split(' ')[0]
    dado = dado.strip() 
    if dado == '':
        dado = 0
    return float(dado)

In [10]:
# para cada nome de carro, aplicamos a função para poder pegar a marca
carros['nome'] = carros['nome'].apply(pegar_marca_do_carro)
carros['consumo'] = carros['consumo'].apply(limpar_dado)
carros['potencia_maxima'] = carros['potencia_maxima'].apply(limpar_dado)
carros['motor'] = carros['motor'].apply(limpar_dado)


In [11]:
carros['proprietario'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [12]:
carros['nome'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'],
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,27,28,29,30,31]
,inplace = True)

C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\388574573.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  carros['nome'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\388574573.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasti

In [13]:
carros['transmissao'].replace(['Manual', 'Automatic'], [1,2],inplace=True)

C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\509718250.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  carros['transmissao'].replace(['Manual', 'Automatic'], [1,2],inplace=True)
C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\509718250.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  car

In [14]:
carros["proprietario"].replace(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'],
                                [1, 2, 3, 4, 5], inplace=True)

C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\3382415106.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  carros["proprietario"].replace(['First Owner', 'Second Owner', 'Third Owner',
C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\3382415106.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`


In [15]:
carros["combustivel"].replace(['Diesel', 'Petrol', 'LPG', 'CNG'], [1, 2, 3, 4], inplace=True)

C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\3564467469.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  carros["combustivel"].replace(['Diesel', 'Petrol', 'LPG', 'CNG'], [1, 2, 3, 4], inplace=True)
C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\3564467469.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downc

array([1, 2, 3, 4])

In [16]:
carros["tipo_vendedor"].replace(['Individual', 'Dealer', 'Trustmark Dealer'],
                                [1, 2, 3], inplace=True)

C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\719078216.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  carros["tipo_vendedor"].replace(['Individual', 'Dealer', 'Trustmark Dealer'],
C:\Users\joaov\AppData\Local\Temp\ipykernel_9576\719078216.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  

In [17]:
dados_input = carros.drop(columns=["preco_venda"])
dados_output = carros["preco_venda"]

In [18]:
x_train, x_test, y_train, y_test = train_test_split(dados_input, dados_output, test_size=0.2)

In [19]:
# criação do modelo

In [20]:
modelo = LinearRegression()

In [22]:
modelo.fit(x_train,y_train)

LinearRegression()

In [21]:
#Train model

In [23]:
predicao = modelo.predict(x_test)

In [24]:
predicao

array([ 425146.57099502, -434220.31448935,  655284.10453852, ...,
        355119.27942578,  499512.03322798,  477941.10145622])

In [25]:
x_train.head(1)

nome   ano  km_rodados  combustivel  tipo_vendedor  transmissao  \
5936     3  2018       30000            2              1            1   

      proprietario  consumo   motor  potencia_maxima  assentos  
5936             1     17.5  1199.0             88.7       5.0

In [26]:
input_modelo_dados = pd.DataFrame(
    [[5,2015,30000,2,1,1,1,17.71,1197.0,78.9,5.0]],
    columns = ['nome', 'ano', 'km_rodados', 'combustivel', 'tipo_vendedor', 'transmissao', 'proprietario', 'consumo', 'motor', 'potencia_maxima', 'assentos']
)


In [27]:
modelo.predict(input_modelo_dados)

array([451287.35174821])

In [28]:
import pickle as pk

In [29]:
pk.dump(modelo, open('modelo.pkl','wb'))